all:
  vars:
    ansible_user: ubuntu

  children:
    ias_nodes:
      hosts:
        "IAS_3.8":
          ansible_host: 192.168.3.43
        "IAS_5.0":
          ansible_host: 192.168.6.11
        "IAS_4.2":
          ansible_host: 192.168.7.11
